/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module binToAscii_10 (
    input num,
    output reg [2:0] ascii
  );
  
  
  
  reg current;
  
  always @* begin
    current = num;
    if (num < 7'h64) begin
      ascii[2+0-:1] = 1'h0;
    end else begin
      if (num < 8'hc8) begin
        ascii[2+0-:1] = 1'h1;
        current = current - 7'h64;
      end else begin
        ascii[2+0-:1] = 2'h2;
        current = current - 8'hc8;
      end
    end
    if (current < 4'ha) begin
      ascii[1+0-:1] = 1'h0;
    end else begin
      if (current < 5'h14) begin
        ascii[1+0-:1] = 1'h1;
        current = current - 4'ha;
      end else begin
        if (current < 5'h1e) begin
          ascii[1+0-:1] = 2'h2;
          current = current - 5'h14;
        end else begin
          if (current < 6'h28) begin
            ascii[1+0-:1] = 2'h3;
            current = current - 5'h1e;
          end else begin
            if (current < 6'h32) begin
              ascii[1+0-:1] = 3'h4;
              current = current - 6'h28;
            end else begin
              if (current < 6'h3c) begin
                ascii[1+0-:1] = 3'h5;
                current = current - 6'h32;
              end else begin
                if (current < 7'h46) begin
                  ascii[1+0-:1] = 3'h6;
                  current = current - 6'h3c;
                end else begin
                  if (current < 7'h50) begin
                    ascii[1+0-:1] = 3'h7;
                    current = current - 7'h46;
                  end else begin
                    if (current < 7'h5a) begin
                      ascii[1+0-:1] = 4'h8;
                      current = current - 7'h50;
                    end else begin
                      ascii[1+0-:1] = 4'h9;
                      current = current - 7'h5a;
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    ascii[0+0-:1] = current;
  end
endmodule
