/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module randomizer_29 (
    input clk,
    input rst,
    input [31:0] numSeed,
    input [31:0] clkSeed,
    output reg [2:0] ranNum,
    output reg [2:0] ranClk,
    input randnumNext,
    input randclkNext,
    input randnumrst,
    input randclkrst,
    input numbregEn,
    input clkregEn
  );
  
  
  
  wire [3-1:0] M_numbreg1_out;
  reg [1-1:0] M_numbreg1_en;
  reg [3-1:0] M_numbreg1_data;
  register_34 numbreg1 (
    .clk(clk),
    .rst(rst),
    .en(M_numbreg1_en),
    .data(M_numbreg1_data),
    .out(M_numbreg1_out)
  );
  wire [3-1:0] M_clkreg_out;
  reg [1-1:0] M_clkreg_en;
  reg [3-1:0] M_clkreg_data;
  register_34 clkreg (
    .clk(clk),
    .rst(rst),
    .en(M_clkreg_en),
    .data(M_clkreg_data),
    .out(M_clkreg_out)
  );
  wire [32-1:0] M_numb_gen_num;
  reg [1-1:0] M_numb_gen_rst;
  reg [1-1:0] M_numb_gen_next;
  reg [32-1:0] M_numb_gen_seed;
  pn_gen_36 numb_gen (
    .clk(clk),
    .rst(M_numb_gen_rst),
    .next(M_numb_gen_next),
    .seed(M_numb_gen_seed),
    .num(M_numb_gen_num)
  );
  wire [32-1:0] M_clk_gen_num;
  reg [1-1:0] M_clk_gen_rst;
  reg [1-1:0] M_clk_gen_next;
  reg [32-1:0] M_clk_gen_seed;
  pn_gen_36 clk_gen (
    .clk(clk),
    .rst(M_clk_gen_rst),
    .next(M_clk_gen_next),
    .seed(M_clk_gen_seed),
    .num(M_clk_gen_num)
  );
  
  always @* begin
    M_numb_gen_rst = rst;
    M_numb_gen_next = randnumNext;
    M_numb_gen_seed = numSeed;
    M_numb_gen_rst = randnumrst;
    M_numbreg1_data = M_numb_gen_num[0+2-:3];
    M_numbreg1_en = numbregEn;
    ranNum = M_numbreg1_out;
    M_clk_gen_rst = rst;
    M_clk_gen_rst = randclkrst;
    M_clk_gen_next = randclkNext;
    M_clk_gen_seed = clkSeed;
    M_clkreg_data = M_clk_gen_num[0+2-:3];
    M_clkreg_en = clkregEn;
    ranClk = M_clkreg_out;
  end
endmodule
